import type { SystemEdge } from './graph';

/**
 * Connections between parts, at the finest level that is true. A collapsed
 * box inherits every edge of its members, so the top view stays readable.
 */
export const edges: SystemEdge[] = [
	/* guest to QEMU to daemon */
	{ from: 'guest-fs', to: 'guest-blk', label: 'block requests · FLUSH' },
	{ from: 'guest-blk', to: 'qemu-ram', label: 'descriptor chains' },
	{ from: 'guest-blk', to: 'qemu-socket', label: 'kick eventfd', dashed: true },
	{ from: 'qemu-socket', to: 'vendor-backend', label: 'vhost-user messages + FDs' },
	{ from: 'qemu-ram', to: 'request', label: 'mapped guest memory' },
	{ from: 'qemu-carrier', to: 'carrier', label: 'sealed memfd' },
	{ from: 'guest', to: 'kvm', label: 'vCPUs run under', dashed: true },

	/* inside the frontend */
	{ from: 'vendor-backend', to: 'frontier', label: 'handle_event' },
	{ from: 'vendor-backend', to: 'lifecycle', label: 'state-change hooks' },
	{ from: 'frontier', to: 'request', label: 'decode chain' },
	{ from: 'frontier', to: 'carrier', label: 'DISCOVERED' },
	{ from: 'frontier', to: 'fe-admission', label: 'head + read candidate' },
	{ from: 'fe-admission', to: 'fair', label: 'ticket · turn' },
	{ from: 'fe-admission', to: 'local', label: 'prepare(kind)' },
	{ from: 'fe-admission', to: 'pending', label: 'accepted' },
	{ from: 'pending', to: 'carrier', label: 'PREPARED → ACTIVE' },
	{ from: 'lifecycle', to: 'local', label: 'pause · resume' },
	{ from: 'fe-recovery', to: 'carrier', label: 'attach · reconcile' },
	{ from: 'fe-recovery', to: 'host-recovery', label: 'Validated bundle' },
	{ from: 'service', to: 'vendor-backend', label: 'listener · shutdown' },
	{ from: 'observability', to: 'frontend', label: 'hooks', dashed: true },

	/* frontend to reactor */
	{ from: 'local', to: 'window', label: 'reserve slot' },
	{ from: 'local', to: 'pools', label: 'credits' },
	{ from: 'local', to: 'quiesce', label: 'enter' },
	{ from: 'local', to: 'reactor', label: 'Command mailbox + eventfd' },
	{ from: 'reactor', to: 'local', label: 'Completed mailbox + eventfd' },
	{ from: 'local', to: 'wal-format', label: 'Builder gather' },
	{ from: 'window', to: 'capacity', label: 'staging / physical check' },
	{ from: 'pools', to: 'budget', label: 'Share · Lease' },
	{ from: 'reactor', to: 'gates', label: 'publish under gate' },
	{ from: 'frontend', to: 'gates', label: 'hold through used entry' },

	/* reactor to core and kernel */
	{ from: 'reactor', to: 'wal-submit', label: 'prepare · publish · fence · sync' },
	{ from: 'reactor', to: 'io-uring', label: 'SQE / CQE' },
	{ from: 'reactor', to: 'scheduler', label: 'ready · take' },
	{ from: 'read', to: 'wal-read', label: 'read plan' },
	{ from: 'read', to: 'man-file', label: 'View::lookup' },
	{ from: 'read', to: 'man-cache', label: 'page hit / fill' },
	{ from: 'read', to: 'cache', label: 'get · fill' },
	{ from: 'read', to: 'fills', label: 'leader / waiter' },
	{ from: 'read', to: 'store-read', label: 'plan(hash)' },
	{ from: 'port', to: 'wal-compaction', label: 'select · publish' },
	{ from: 'port', to: 'wal-reclaim', label: 'select · apply' },
	{ from: 'port', to: 'wal-segment', label: 'prepare · install rotation' },
	{ from: 'port', to: 'owner', label: 'Ready turns · Event/Reply' },

	/* owner */
	{ from: 'compact', to: 'wal-compaction', label: 'load · prepare · write' },
	{ from: 'compact', to: 'store-insert', label: 'insert chunks' },
	{ from: 'compact', to: 'man-file', label: 'prepare · publish' },
	{ from: 'compact', to: 'capacity', label: 'background promise' },
	{ from: 'rotate', to: 'wal-segment', label: 'create segment' },
	{ from: 'collect', to: 'quiesce', label: 'pause · resume' },
	{ from: 'collect', to: 'store-collection', label: 'mark · sweep' },
	{ from: 'collect', to: 'man-reclaim', label: 'punch pages' },
	{ from: 'snapshot', to: 'man-snapshot', label: 'reflink' },
	{ from: 'snapshot', to: 'catalog', label: 'insert entry' },
	{ from: 'owner', to: 'scheduler', label: 'background turn per syscall' },
	{ from: 'owner', to: 'direct', label: 'blocking pread / pwrite / sync' },
	{ from: 'capacity', to: 'space', label: 'Staging · Governor' },
	{ from: 'fair', to: 'quiesce', label: 'wake frontends' },

	/* host lifecycle */
	{ from: 'hostsvc', to: 'host-recovery', label: 'scan · recover' },
	{ from: 'hostsvc', to: 'service', label: 'one per image' },
	{ from: 'host-recovery', to: 'catalog', label: 'inspect' },
	{ from: 'host-recovery', to: 'store-recovery', label: 'inspect · rebuild index' },
	{ from: 'host-recovery', to: 'man-file', label: 'inspect · recover' },
	{ from: 'host-recovery', to: 'wal-recovery', label: 'inspect · fresh · live' },
	{ from: 'host-recovery', to: 'tickets', label: 'open · lock' },
	{ from: 'storage-enum', to: 'local', label: 'Local variant' },
	{ from: 'storage-enum', to: 'staging-v1', label: 'Staging variant' },
	{ from: 'storage-enum', to: 'io-uring', label: 'Raw variant' },

	/* inside cas-core */
	{ from: 'wal-submit', to: 'wal-format', label: 'seal · decode' },
	{ from: 'wal-submit', to: 'wal-index', label: 'publish mappings' },
	{ from: 'wal-read', to: 'wal-index', label: 'overlapping' },
	{ from: 'wal-read', to: 'wal-segment', label: 'pin batch' },
	{ from: 'wal-compaction', to: 'chunk', label: 'BLAKE3' },
	{ from: 'wal-compaction', to: 'man-tree', label: 'Prepared::build' },
	{ from: 'wal-recovery', to: 'space', label: 'governed repair' },
	{ from: 'wal-segment', to: 'tickets', label: 'allocate' },
	{ from: 'store-insert', to: 'chunk-index', label: 'reserve · publish' },
	{ from: 'store-insert', to: 'store-format', label: 'seal batch' },
	{ from: 'store-insert', to: 'tickets', label: 'new segment' },
	{ from: 'store-read', to: 'chunk-index', label: 'lookup' },
	{ from: 'store-collection', to: 'chunk-index', label: 'mark · relocate · remove' },
	{ from: 'store-recovery', to: 'chunk-index', label: 'insert inline hashes' },
	{ from: 'man-file', to: 'man-tree', label: 'Lookup · Prepared' },
	{ from: 'man-file', to: 'man-pins', label: 'Pin per View' },
	{ from: 'man-tree', to: 'man-format', label: 'decode · encode' },
	{ from: 'man-reclaim', to: 'man-pins', label: 'capture roots' },
	{ from: 'man-cache', to: 'lru', label: 'shared Lru' },
	{ from: 'cache', to: 'lru' },
	{ from: 'fills', to: 'ipc', label: 'eventfd signal' },
	{ from: 'scheduler', to: 'ipc', label: 'eventfd wake' },
	{ from: 'channel', to: 'budget', label: 'charged ring' },
	{ from: 'space', to: 'xfs', label: 'fstatvfs' },
	{ from: 'space', to: 'tickets', label: 'root fd' },
	{ from: 'catalog', to: 'direct', label: 'temp · sync · rename' },
	{ from: 'direct', to: 'scheduler', label: 'before_background_io' },
	{ from: 'direct', to: 'xfs', label: 'open · write · sync · punch · reflink' },
	{ from: 'wal-segment', to: 'direct' },
	{ from: 'store-insert', to: 'direct' },
	{ from: 'man-file', to: 'direct' },
	{ from: 'man-snapshot', to: 'direct', label: 'FICLONE' },
	{ from: 'append', to: 'budget', label: 'metadata charges' },
	{ from: 'manifest', to: 'budget', label: 'metadata charges' },
	{ from: 'cache', to: 'budget', label: 'payload budget' },
	{ from: 'chunk-index', to: 'budget', label: 'BudgetAllocator' },

	/* on disk */
	{ from: 'wal-segment', to: 'f-staging', label: 'segment files' },
	{ from: 'store-insert', to: 'f-chunks', label: 'chunk batches' },
	{ from: 'man-file', to: 'f-manifest', label: 'pages + COMMIT' },
	{ from: 'catalog', to: 'f-catalog', label: 'catalog.v2' },
	{ from: 'man-snapshot', to: 'f-snapshots', label: 'reflinked manifest' },
	{ from: 'hostsvc', to: 'f-outside', label: 'reports · telemetry' },
	{ from: 'xfs', to: 'disk', label: 'holds', dashed: true },

	/* tooling */
	{ from: 'nix', to: 'workspace', label: 'buildRustPackage' },
	{ from: 'nix', to: 'nix-guest', label: 'NixOS systems' },
	{ from: 'nix-guest', to: 'qemu', label: 'run-cas-*-vm launcher' },
	{ from: 'h-vm', to: 'qemu', label: 'spawns guest' },
	{ from: 'h-vm', to: 'host', label: 'spawns cas-daemon' },
	{ from: 'h-fixture', to: 'host', label: 'cas-host init · serve · SIGKILL' },
	{ from: 'h-suite', to: 'h-vm', label: 'scenarios' },
	{ from: 'h-suite', to: 'h-fixture', label: 'scenarios' },
	{ from: 'h-suite', to: 'h-pressure', label: 'C5' },
	{ from: 'h-suite', to: 'h-persistence', label: 'C3' },
	{ from: 'h-persistence', to: 'append', label: 'Log::open on schedules' },
	{ from: 'h-fleet', to: 'census', label: 'casctl census' },
	{ from: 'casctl', to: 'host', label: 'cas-host in the lab VM' },
	{ from: 'casctl', to: 'guest', label: 'ssh · fio bench' },
	{ from: 'casctl', to: 'staging-v1', label: 'staging-check' },
	{ from: 'harness', to: 'evidence', label: 'typed reports' },
	{ from: 'casctl', to: 'evidence', label: 'runs/ samples' },
	{ from: 'ci', to: 'h-suite', label: 'dispatch: C5' },
	{ from: 'ci', to: 'h-vm', label: 'smoke · recovery · live' },
	{ from: 'nix-host', to: 'kernel', label: 'dedicated hosts (pending)', dashed: true },
	{ from: 'hostsvc', to: 'evidence', label: 'host.json · telemetry.jsonl' }
];
