[package]
name = "cas-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
allocator-api2.workspace = true
arena-btreemap.workspace = true
arrayvec.workspace = true
blake3.workspace = true
hashbrown.workspace = true
serde.workspace = true
crc32fast.workspace = true
libc.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
